config/routes.rb
Blog::Application.routes.draw do

root :to => 'posts#index'

post '/posts/search' => 'posts#find', :as => :find_posts 
get '/posts/search' => 'posts#search', :as => :search_posts
get '/posts' => 'posts#index', :as => :posts
post '/posts' => 'posts#create'
get '/posts/new' => 'posts#new', :as => :new_post
get '/posts/:id' => 'posts#show', :as => :post
get '/posts/:id/edit' => 'posts#edit', :as => :edit_post
put '/posts/:id' => 'posts#update'
delete '/posts/:id' => 'posts#destroy'
post '/posts/:post_id/comments' => 'comments#create'
delete '/posts/:post_id/comments/:id' => 'comments#destroy'
get '/posts/:id/comments/new' => 'comments#new', :as => :new_comment
resources :user_sessions
resources :users

match 'login' => "user_sessions#new",      :as => :login
match 'logout' => "user_sessions#destroy", :as => :logout

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :author,  :presence => true
	belongs_to :post
end

app/models/mark.rb
class Mark < ActiveRecord::Base
		validates :value, :numericality => {:greater_than => 0, :less_than => 6}
		has_many :post_scores
		has_many :posts, :through => :post_scores
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, :dependent => :destroy
end

app/models/post_score.rb
class PostScore < ActiveRecord::Base
	belongs_to :post
	belongs_to :mark
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end
end

    def require_user
      unless current_user
        flash[:notice] = "You must be logged in to access this page"
        redirect_to posts_path
        return false
      end
    end

    def require_no_user
      if current_user
        flash[:notice] = "You must be logged out to access this page"
        redirect_to account_url
        return false
      end
    end

    def redirect_back
      redirect_to(session[:return_to])
      session[:return_to] = nil
    end
		
		def redirect_to_root(notice)
			flash[:notice] = notice
			redirect_to '/'
		end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :require_user, :only => :destroy
	def new
		@post = Post.find(params[:id])
		respond_to do |format|
			format.js
			format.html
		end
	end

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(:author => params[:comment_author], :body => params[:comment_body])
		respond_to do |format|
			format.js
			format.html { redirect_to post_path(@post) }
		end
	end
	
	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :require_user, :except => [:index, :show, :search, :find]

	def index
		@posts = Post.all
		respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
	end

	def new
		@post = Post.new
		render
	end

	def create
		@post = Post.create(params[:post])
		redirect_to posts_path
	end
	
	def show
		@post = Post.find(params[:id])
		render
	end

  def edit
    @post = Post.find(params[:id])
    render
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to post_path(@post), notice: 'Post was successfully updated.' # @post <=> post[@post.id]
    else
      render action: "edit"
    end
  end

	def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

	def search
		render
	end

	def find
		titre = params[:search_title]
		corps = params[:search_body]
		
		if titre.empty? 
			if corps.empty?
				@posts = Post.all
			else 
				#recherche seulement dans le corps des posts
				@posts = Post.find(:all, :conditions => ['body LIKE ?', '%' + corps + '%' ] )
				puts "ICI : " + @posts.find.inspect
			end
		else	#recherche dans le titre
				if corps.empty?
					#recherche seulement dans le titre
					@posts = Post.find(:all,:conditions => ['title LIKE ?', '%' + titre + '%' ] )
				else 
					#recherche dans le titre et le corps
					@posts = Post.find(:all, :conditions => ['title LIKE ?', '%' + titre + '%' ], :conditions => ['body LIKE ?', '%' + corps + '%' ] )
				end
		end
		render 'index'
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
		respond_to do |format|
			format.js
			format.html
		end
  end

  def create
		@user_session = UserSession.new(:login => params[:login], :password => params[:password])
		if @user_session.save
			flash[:notice] = "Login successful!"
			respond_to do |format|
				format.js
				format.html {redirect_to '/'}
			end
		else
			flash[:notice] = "Login error!"
			respond_to do |format|
				format.js {render 'login_error.js.erb'}
				format.html {redirect_to '/login'}
			end
		end

  end

  def destroy
    current_user_session.destroy
		flash[:notice] = "Logout successful!"
		respond_to do |format|
			format.js
			format.html {redirect_to :back}
		end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :require_user

  def new
		@user = User.new
		render
  end

  def create
		puts "PARAMS : " + params.inspect
		@user = User.new(:login => params[:login], :email => params[:email], :password => params[:password], :password_confirmation => params[:password_confirmation])
		if @user.save
			flash[:notice] = 'User created sucessfully'
		else
			flash[:notice] = 'Error : user not created'
		end
		redirect_to posts_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_tag "/posts/#{@post.id}/comments" %>
	<h2 class="form_title">Comment this post</h2>
	<div class="sep"></div>
	<div class="form_row">
		<div class="field">
		  <%= label_tag :author %>
		  <%= text_field_tag :comment_author %>
		</div>
	</div>
	<div class="sep"></div>
	<div class="form_row">
		<div class="field">
		  <%= label_tag :comment %><br />
		  <%= text_area_tag :comment_body %>
		</div>
	</div>
  <div class="button">
    <%= submit_tag value = "Comment" %>
  </div>

app/views/comments/_list.html.erb
<h3 class="title_blue">Comments</h3>
<% @post.comments.each do |comment| %>
<div class="anx">	
	<div class="box_blue_no_img">
		<div class="box_in">
			<div class="c_blue"></div>
			<h3><%= comment.author %></h3>
<% if current_user %>
			<div class="is_admin">
<%else%>
			<div class="is_not_admin">
<%end%>
				<p><%= link_to 'Delete Comment', "/posts/#{@post.id}/comments/#{comment.id}",
		             :confirm => 'Are you sure?',
		             :method => :delete%>
				</p>
			</div>
			<p class="p_spacer"><%= comment.body %></p>
		</div>
	</div>
</div>
<% end %>

app/views/comments/create.js.erb
$("a[href='<%= new_comment_path(@post.id) %>']").fadeIn();
$("a[href='<%= new_comment_path(@post.id) %>']").before("<div class='anx'> <div class='box_blue_no_img'> 		<div class='box_in'> 			<div class='c_blue'></div> 			<h3><%= escape_javascript(@comment.author) %></h3> 	<%if current_user%>		<p><%= escape_javascript(link_to 'Delete Comment', "/posts/#{@post.id}/comments/#{@comment.id}", 		             :confirm => 'Are you sure?', 		             :method => :delete)%> 			</p><%end%> 			<p class='p_spacer'><%= escape_javascript(@comment.body) %></p> 		</div> 	</div> </div>");

$(".form_container").remove();

app/views/comments/new.html.erb
<div class='form_container'>
	<%=render 'comments/form'%>
	
	<p><%= link_to 'Back', post_path(@post) %></p>
</div>

app/views/comments/new.js.erb
$(".form_container").remove();
$("a[href='<%= new_comment_path(@post.id) %>']").after("<div class='form_container'>");
$("<div class='form_container'>").after("</div>");
$(".form_container").append("<%= escape_javascript(render 'comments/form') %>");
$("form").attr("data-remote", true);
$("a[href='<%= new_comment_path(@post.id) %>']").fadeOut();

app/views/layouts/_header.html.erb
<div class="header clear_fix">
<div class="header_left header_title">Blog de Sylvain AUGUY</div>
<div class="header_right"></div>
</div>

app/views/layouts/_menu.html.erb
<div class="box box_gray">
		<div class="top"></div>
		<div class="box_gray_inner">
			<h2 class="cartouche">Account</h2>
			<div class="middle clear_fix">
					<% if current_user %>
						<div class="account">
							<p>Logged as 	<b><%=current_user.login%></b></p>
							<p>Mail : <b><%=current_user.email%></b></p>
						</div>
						<%= link_to "Log out", logout_path, :remote => true %>
					<% else %>
						<%= link_to "Log in", login_path, :remote => true %>
					<%end%>
			</div>
			<h2 class="cartouche">Navigation</h2>
			<div class="middle clear_fix">
				<p><%= link_to 'Index', posts_path %></p>
				<p><%= link_to 'Search a post', search_posts_path %></p>
			</div>
	</div>
</div>

<% if current_user %>
<div class="is_admin">
<%else%>
<div class="is_not_admin">
<%end%>
	<div class="box box_gray">
		<div class="top"></div>
		<div class="box_gray_inner">
				<h2 class="cartouche">Administration</h2>
				<div class="middle clear_fix">
					<p><%= link_to 'New Post', new_post_path %></p>
					<p><%= link_to 'Create user', new_user_path %></p>
				</div>
			</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag	"application" %>
	<%= stylesheet_link_tag "styles"%>
	<%= stylesheet_link_tag "box"%>
	<%= stylesheet_link_tag "global"%>
	<%= stylesheet_link_tag "user_sessions"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">
	<%=render "layouts/header" %>
	<div class="content_duality clear_fix">
		<% if flash[:notice] %>
		<div class="flash">
			<%= flash[:notice] %>
		</div>
		<%end%>
		<div class="columns_left_middle"><%= yield %></div>
		<div class="columns_right">
			<%=render "layouts/menu" %>
		</div>
	</div>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
		<div class="sep"></div>
		<div class="form_row">
				<div class="field">
				<%= f.label :title %>
				<%= f.text_field :title %>
			</div>
		</div>
		<div class="sep"></div>
		<div class="form_row">
			<div class="field">
				<%= f.label :body %><br />
				<%= f.text_area :body %>
			</div>
		</div>
			<div class="button">
				<%= f.submit %>
			</div>
<% end %>

app/views/posts/edit.html.erb
<div class="form_container">
	<h2 class="form_title">Edit post</h2>
	<%= render 'form' %>
</div>
<%= link_to 'Back', post_path(@post) %>

app/views/posts/index.html.erb
<h1 class="title_blue">Listing posts</h1>

<% @posts.each do |post| %>
<div class="columns_left_middle">
	<div class="box box_blue_shade">
		<h2 class="top"><%= post.title %></h2>
		<div class="middle clear_fix">
<% if current_user %>
			<div class="is_admin">
<%else%>
			<div class="is_not_admin">
<%end%>
				<p><%= link_to 'Edit', edit_post_path(post.id) %> <%= link_to 'Delete', post_path(post.id), :method => :delete %></p>
			</div>
			<p class="p_spacer">
	<% if post.body.length < 400 %>
			<%= post.body %>
	<%else%>
			<%= post.body[0..400]+" ..." %>
	<%end%>
			</p>
			<p><%= link_to 'Show', post_path(post.id) %></p>
		</div>
	</div>
</div>
<% end %>

app/views/posts/new.html.erb
<div class="form_container">
	<h2 class="form_title">Create a new post</h2>
	<%= render 'form' %>
</div>

<%= link_to 'Back', posts_path %>

app/views/posts/search.html.erb
<div class='form_container'>
	<div class='box box_gray'>
		<div class='top'></div>
		<div class='box_gray_inner'>
			<h2 class='cartouche'>Search a post</h2>
			<div class='middle clear_fix'>
				<%= form_tag find_posts_path %>
				<div class="search_field">
					<p><%= label_tag :Title %><%= text_field_tag :search_title %></p>

					<p><%= label_tag :Body %><%= text_field_tag :search_body %></p>
					<div class='button'>
				<%= submit_tag value = 'Search' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
	<div class="box box_orange_shade">
		<h2 class="top"><%= @post.title %></h2>
		<div class="middle clear_fix">
			<% if current_user %>
			<div class="is_admin">
			<%else%>
			<div class="is_not_admin">
			<%end%>
				<p><%= link_to 'Edit', edit_post_path(@post)%>
			</div>
			<p class="p_spacer"><%= @post.body %></p>
		</div>
	</div>
	<div class="comments">
		<%= render 'comments/list' %>
		<%= link_to 'Add a comment', new_comment_path(@post.id), :remote => true%>
		
	</div>

app/views/user_sessions/_form.html.erb
<div class='box box_gray'>
	<div class='top'></div>
	<div class='box_gray_inner'>
		<h2 class='cartouche'>Login</h2>
		<div class='middle clear_fix'>
			<%= form_tag '/user_sessions' %>
			<div class='login_field'>
				<p><%= label_tag :login %><%= text_field_tag :login %></p>

				<p><%= label_tag :password %><%= password_field_tag :password %></p>

				<div class='button'>
					<%= submit_tag value = 'Login' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/user_sessions/create.js.erb
$("a[href='<%=login_path%>']").fadeIn();
$("a[href='<%=login_path%>']").before("<div class='account'><p>Logged as 	<b><%=escape_javascript(params[:login])%></b></p></div>");
$("a[href='<%=login_path%>']").before("<a data-remote='true' href='/logout' >Log out</a>");
$("a[href='<%=login_path%>']").remove();
$("div[class='box box_gray']:last").remove();
$('.content_duality').prepend("<% if flash[:notice] %><div class='flash'><%= escape_javascript(flash[:notice]) %></div><%end%>");
<%flash[:notice]=nil%>
$('.is_not_admin').each(function() {
    $(this).attr("class", "is_admin");
	}
);

app/views/user_sessions/destroy.js.erb
$("a[href='<%=logout_path%>']").before("<a data-remote='true' href='/login' >Log in</a>");
$("a[href='<%=logout_path%>']").remove();
$(".account").remove();
$('.content_duality').prepend("<% if flash[:notice] %><div class='flash'><%= escape_javascript(flash[:notice]) %></div><%end%>");
<%flash[:notice]=nil%>
$('.is_admin').each(function() {
    var $div = $(this);
    $div.attr("class", "is_not_admin");
	}
);

app/views/user_sessions/login_error.js.erb
$("div[class='box box_gray']:last").remove();
$("a[href='<%=login_path%>']").fadeIn();
$('.content_duality').prepend("<% if flash[:notice] %><div class='flash'><%= escape_javascript(flash[:notice]) %></div><%end%>");
<%flash[:notice]=nil%>

app/views/user_sessions/new.html.erb
<div class='form_container'>
	<%=render 'user_sessions/form'%>
	
	<p><%= link_to 'Back', posts_path %></p>
</div>

app/views/user_sessions/new.js.erb
$("a[href='<%=login_path%>']").fadeOut();
$(".columns_right").append("<div class='box box_gray'>	<div class='top'></div>	<div class='box_gray_inner'>		<h2 class='cartouche'>Login</h2>		<div class='middle clear_fix'>			<div class='form_container'><%= escape_javascript(form_tag '/user_sessions') %>			<div class='login_field'>				<p><%=escape_javascript(label_tag :login) %><%=escape_javascript(text_field_tag :login) %></p>				<p><%=escape_javascript(label_tag :password) %><%=escape_javascript(password_field_tag :password) %></p>				<div class='button'>					<%=escape_javascript(submit_tag value = 'Login')%>				</div>			</div>		</div>	</div></div></div>");
$("form").attr("data-remote", true);

app/views/users/_form.html.erb
<div class='box box_gray'>
	<div class='top'></div>
	<div class='box_gray_inner'>
		<h2 class='cartouche'>Create a new user</h2>
		<div class='middle clear_fix'>
			<%= form_tag '/users' %>
			<div class='login_field'>
				<p><%= label_tag :login %><%= text_field_tag :login %></p>
				<p><%= label_tag :email %><%= text_field_tag :email %></p>
				<p><%= label_tag :password %><%= password_field_tag :password %></p>
				<p><%= label_tag :password_confirmation %><%= password_field_tag :password_confirmation %></p>
				<div class='button'>
					<%= submit_tag value = 'Create' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class='form_container'>
	<%=render 'users/form'%>
	
	<p><%= link_to 'Back', posts_path %></p>
</div>